logo()                                                        
Printf("                          ##                          \n");
Printf("                         #$##                         \n");
Printf("                        ## $#                         \n");
Printf("                       ##   ##                        \n");
Printf("                       #$    ##                       \n");
Printf("                      ##      #@                      \n");
Printf("                     ##       @#                      \n");
Printf("                    $#         ##                     \n");
Printf("                    ##          ##                    \n");
Printf("########## ######### $$       $#@ ####################\n");
Printf("   ###           @####     ##   ##$             ###   \n");
Printf("     $##@        $  ##     #$    ##          ###      \n");
Printf("        @##@        ##    ##     $#       ###         \n");
Printf("           @##      ##    ##     $#    ###            \n");
Printf("              @##   ##    ##     $# @##               \n");
Printf("               #@   ##    @#     ##  ##               \n");
Printf("              ##    ##     ##   ##$  $#               \n");
Printf("             @#  #######$   @####     ##              \n");
Printf("             #@          ###@          #@             \n");
Printf("            ##        ###   @##@       @#             \n");
Printf("           @#     $###         $###     ##            \n");
Printf("           ##  $###                ###   #@           \n");
Printf("          ##@##$                      ###@#           \n");
Printf("          ##                             ###          \n");
Printf("\n Ушкова Анита ИВТ-12\n");
Printf("Нажмите Enter!\n");
getchar();